services:
  - type: web
    name: letsconnect-backend
    env: node
    plan: free

    buildCommand: >
      apt-get update &&
      apt-get install -y ffmpeg &&
      npm ci &&
      npx prisma generate &&
      npm run build

    startCommand: npm run start:prod
